services:
  - type: web
    name: pgoldapi
    runtime: image
    repo: https://github.com/Vikiwest/PGoldApi
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://pgoldapi.onrender.com
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: L5_SWAGGER_GENERATE_ALWAYS
        value: false
